# Generated by Django 5.2 on 2025-05-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
